parameters:
- name: 'HELM_VERSION'
  type: string
  default: '3.4.2'

steps:
- template: '../unzip/install.yaml'

- task: HelmInstaller@0
  displayName: Install Helm
  inputs:
    helmVersion: ${{parameters.HELM_VERSION}}
